### ISSUE TITLE
Android 10: gesture navigation conflict

### ISSUE THREAD

**Issue by Shusshu** [pandulapeter/beagle#1]
Do you have a solution to make this work together with gesture navigation on Android 10 ?

**Comment by pandulapeter** [comment]
Hi! Thanks for raising the issue.

I've tested the example app on Android 10: as I'm using the latest DrawerLayout dependency, the gesture is supported. It's not the most intuitive thing ever: if you swipe horizontally from the right edge of the screen, it registers as Back but if you swipe diagonally from the right (towards the top or the lower edge of the device) it will nicely open the debug menu. Give it a try and let me know if you have any issues!

I'm thinking about adding an optional "shake to open" gesture. Also, there is a behavior that should work and it doesnt: long pressing on the edge of the screen should also open the drawer instead of trigerring the back action - I'll probably have to modify the screen insets a bit. I'll leave this issue open until these two problems are fixed, but the library should be usable currently with gesture navigation, if you follow the steps mentioned above.

**Comment by Shusshu** [comment]
Oh nice - I can use that gesture for other apps too 
Not the best experience but you ROCK 🚀
