### ISSUE TITLE
Coil update

### ISSUE THREAD

**Issue by emartynov** [pandulapeter/beagle#101]
Problem:
Update to the latest beagle we got coil RC as the transitive dependency that broke compilation and requires some changes.
Going to the Coil RC is not something we are thinking of.

I wonder in general some agreement about the versioning - maybe don't name version stable if it depends on RC. Not sure what is the best practice.

**Comment by pandulapeter** [comment]
Hi,

Migrating to the new Coil version has been requested in another issue. You're right, I should have created a separate RC artifact for Beagle.

For the time being I suggest you keep using version [2.6.7](https://github.com/pandulapeter/beagle/releases/tag/2.6.7), there weren't any significant improvements introduced since then.

I don't plan to include RC versions in the future so let's hope Coil becomes stable soon and we can forget about this situation. I'll keep the thread open till then.

**Comment by emartynov** [comment]
I know it is chicken and egg - on one hand, you want to have it recent, on another consumer of libraries have to follow this requirement.

This was a minor release update - that is not something that will bring API changes. Maybe updating the major version in case of some dependency is also updating to the major version.

In any case, appreciate you're on the latest version and quick reply to my question.

**Comment by pandulapeter** [comment]
Release [2.8.0](https://github.com/pandulapeter/beagle/releases/tag/2.8.0) now depends on only stable versions. Next time I'll try to handle these issues more elegantly.

Keep in mind that starting with this version, Beagle is hosted on MavenCentral and the artifact ID for it should be changed from `com.github.pandulapeter.beagle....` to `io.github.pandulapeter.beagle...`.
