### ISSUE TITLE
Beagle preventing automatic keyboard opening.

### ISSUE THREAD

**Issue by fabiocarballo** [pandulapeter/beagle#19]
Hey,

In a number of screens we have where the soft input keyboard is working, the focus is "stolen" by Beagle, and for that reason the keyboard doesn't open automatically. Do you have any suggestion on how to solve this?

Thanks.

**Comment by pandulapeter** [comment]
Hi!

Thanks for reporting the issue, I wasn't aware of this. The screens where you need the keyboard to appear are Activities or Fragments?

To be honest I had some bad experiences with the soft keyboard's automatic opening on different devices so to be sure, I always manually call for showing / hiding it. `post()`-ing something like this:

`fun showKeyboard(focusedView: View?) = focusedView?.also {
    it.requestFocus()
    (it.context.getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager).showSoftInput(it, 0)
}`

...might be the most certain way to make sure that the keyboard appears. Anyway, I'll need to look into it, the way Beagle is added to the View hierarchy in the Activity's `onCreate()` can definitely mess up things.

Thanks again, I'll let you know if I find something!

**Comment by fabiocarballo** [comment]
The both cases I noticed are Activities hosting Fragments! We are also trying to force the showing of the keyboard. I will check if it is exactly in that way you suggested and if it alleviates the problem. Thanks!

**Comment by rahulsainani** [comment]
Would it be possible to exclude some activities so the drawer is not added on them? Perhaps with lifecycleCallbacks?

**Comment by pandulapeter** [comment]
@rahulsainani I've just released a new version for you: 1.9.0 adds an optional parameter to the `imprint()` method called `excludedActivities` which you can use to specify the classes where you don't want to use Beagle. You can use it like this:

`
Beagle.imprint(
    application = this,
    excludedActivities = listOf(LoginActivity::class.java, AnotherActivity::class.java)
)
`

In the future I might deprecate this API and move to a callback-based solution like you suggested, but right now that would require more effort, hopefully this temporary fix is okay for the time being.

**Comment by pandulapeter** [comment]
@fabiocarballo I definitely managed to reproduce the keyboard issue you mentioned. I usually test with single-Activity apps so that's the reason why I didn't notice... 

As I don't see at the moment how I could fix this from the library, I have two suggestions for you:

1) Keep in mind that the beagle-noop dependency that you should be using in release builds does absolutely nothing so the issue should not be affecting end-users: leave it as it is.
2) Use the hacky workaround I suggested before in a `postDelayed()` call. It seems to be working, you can check it out [here](https://github.com/pandulapeter/beagle/commit/8e7762647e8c804731270510d20016154a8c05c5).

**Comment by rahulsainani** [comment]
Thank you so much for the quick reply and feature! Will try now and update here.

**Comment by fabiocarballo** [comment]
thanks!

**Comment by rahulsainani** [comment]
Working as Intended, thanks again! 👍

**Comment by pandulapeter** [comment]
v2 uses a completely different way to inject itself into the app (instead of re-organizing the original view hierarchy it just adds a Fragment on top of the layout). Hopefully this less hacky solution no longer interferes with focus handling, but if it does, problems can be solved in a per-case basis (and surely won't affect release builds at all).
