### ISSUE TITLE
Ability as all-in-one solutions for QA & Dev debugging task

### ISSUE THREAD

**Issue by mochadwi** [pandulapeter/beagle#24]
I've recently used this [OkReport features](https://github.com/cookpad/OkReport#-okreports-workflow). 

Would be nice if this library also support the following features:
1. multiple screenshot (and able to highlight some area of view) - OkReport
2. multiple repro steps - OkReport
3. submit report to email/slack (for QA able to collect all the repro+screenshot) - OkReport
4. [error log crash reporting](https://github.com/MindorksOpenSource/CrashReporter/) (no need to check for firebase crashlytics to diagnose the crash, because QA will share the crash log, good condition when e.g: AFK)
5. network log ui, like [Chucker](https://github.com/ChuckerTeam/chucker)

EDITED:
Point number 3, as you already planned in README.md, that's GREAT!!!
> `TODO: SendBugReportButton - Sends a pre-formatted message with logs to a specified email address.`

**Comment by pandulapeter** [comment]
Hi! I wasn't familiar with OkReport, thanks! I'll look into how it works when I get around to figuring out that feature, because the main problem there is that I'm not sure about a UX that would work for most projects. Hopefully it will be read soon...

**Comment by pandulapeter** [comment]
Just to give you a quick update as I'm mostly done with rewriting the existing features for v2 of the library and can now start focusing on new stuff. The general idea of this issue is actually a high priority for the library: I'd like to include an error handling module that can generate these reports and maybe create Jira tickets or send them via email (with media attachments).

We now have a way to create [screenshots](https://github.com/pandulapeter/beagle/blob/master/common/src/main/java/com/pandulapeter/beagle/modules/ScreenshotButtonModule.kt) and [screen recordings](https://github.com/pandulapeter/beagle/blob/master/common/src/main/java/com/pandulapeter/beagle/modules/ScreenRecordingButtonModule.kt): the next step is to add a gallery screen where all of these can be accessed (right now they get lost if you don't share them immediately). That gallery screen will probably have options to manage the files (maybe draw on the screenshots?) and create issue reports with them (and also attach device info, network logs, etc - this will be configurable). Sorry for the slow progress but now that more fundamental issues are resolved, this will be the next step.

**Comment by mochadwi** [comment]
Awesome works! Thanks a lot for your time and efforts for this great library :)

**Comment by pandulapeter** [comment]
This took a while but the first version is finally ready in [release v2.2.0](https://github.com/pandulapeter/beagle/releases/tag/2.2.0)! You can now add an instance of [BugReportButtonModule](https://github.com/pandulapeter/beagle/blob/master/common/src/main/java/com/pandulapeter/beagle/modules/BugReportButtonModule.kt) to the debug menu, which will link to a screen like this:

![bugReport](https://user-images.githubusercontent.com/10262638/96490252-3f5e7680-1249-11eb-9dd9-e43ae157dd09.jpg)

Hopefully there aren't too many issues with it, it's a very early version that needs to be tested a lot.

**Comment by mochadwi** [comment]
A big shoutout & really appreciate for your time @pandulapeter

Btw, where can I donate? :)

**Comment by mochadwi** [comment]
> A big shoutout & really appreciate for your time @pandulapeter
> 
> Btw, where can I donate? :)

found the link: https://github.com/pandulapeter/beagle#buy-me-a-beer

**Comment by mochadwi** [comment]
> > A big shoutout & really appreciate for your time @pandulapeter
> > 
> > Btw, where can I donate? :)
> 
> found the link: https://github.com/pandulapeter/beagle#buy-me-a-beer

Done donating, thanks a lot @pandulapeter for this great all in one debugging tools 

Btw, I've experience crash on your showcase apps after successful payment

**Comment by pandulapeter** [comment]
> > > A big shoutout & really appreciate for your time @pandulapeter
> > > Btw, where can I donate? :)
> > 
> > 
> > found the link: https://github.com/pandulapeter/beagle#buy-me-a-beer
> 
> Done donating, thanks a lot @pandulapeter for this great all in one debugging tools
> 
> Btw, I've experience crash on your showcase apps after successful payment (low priority)

Thanks a lot, I really appreciate it! :) And thanks for the bugreport, looks like a snackbar / proguard issue, I'm on it

**Comment by mochadwi** [comment]
> (maybe draw on the screenshots?

I haven't tested this module, cmiiw does the above functionality also included? @pandulapeter

**Comment by pandulapeter** [comment]
Drawing on the screenshots is not possible at the moment, this is again something that would be a bigger effort to implement properly (stylus support, color choices, text, etc). As for creating jira tickets, that probably wouldn't scale well to every project (what if somebody uses a different ticketing system). The solution is that by default the library generates a .zip file that can be shared via the system share sheet. Developers can override this behavior (via the onBugReportReady lambda parameter) and get a reference to the URI of that zip file: with that they can implement whatever they want. I might improve this later but for now this was the simplest approach.
