### ISSUE TITLE
Support for custom built Trick

### ISSUE THREAD

**Issue by eric-labelle** [pandulapeter/beagle#26]
Hi, I wonder if you had plans to make it more extensible in a near future? I've seen there is a lots of building blocks and great modules already built-in but I just wonder if you were planning to open Beagle for custom made Tricks.

Thanks and great work on the library! :)

**Comment by pandulapeter** [comment]
Hi!

Due to some not-so-great decisions I made early on this is a bit difficult with the current setup. However, I've been planning for a while to rewrite the core parts of the library and support for custom tricks is actually one of the best reasons to do so :) There will be a v2 of the library in the coming months with breaking changes but a better API and this will definitely be a part of it.

**Comment by pandulapeter** [comment]
Version 2.0.0 (now in alpha) supports this feature :) Thanks again for the idea!
