### ISSUE TITLE
Does Beagle doesn't support API 16 & below? 

### ISSUE THREAD

**Issue by mochadwi** [pandulapeter/beagle#27]
Does Beagle only support **minSdk 17**?
Same SO Questions regarding `marginStart|End`: https://stackoverflow.com/a/25749855/3763032
Error Log:
```
    java.lang.NoSuchMethodError: android.widget.FrameLayout$LayoutParams.setMarginStart
        at com.pandulapeter.beagle.views.BeagleDrawer.<init>(BeagleDrawer.kt:52)
        at com.pandulapeter.beagle.views.BeagleDrawer.<init>(BeagleDrawer.kt:27)
        at com.pandulapeter.beagle.Beagle.createAndAddDrawerLayout(Beagle.kt:355)
        at com.pandulapeter.beagle.Beagle.access$createAndAddDrawerLayout(Beagle.kt:49)
        at com.pandulapeter.beagle.Beagle$lifecycleCallbacks$1.onActivityCreated(Beagle.kt:289)
        at android.app.Application.dispatchActivityCreated(Application.java:154)
        at android.app.Activity.onCreate(Activity.java:887)
        at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:81)
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:154)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:312)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
```

**Comment by pandulapeter** [comment]
I only tested it above API 21 and was not indending to go below that - but if there is a need for it, I can give it a try. As long as the issues are simply with start / end vs left / right, fixing them should not be a big deal, I'm more afraid of theming issues.

**Comment by mochadwi** [comment]
Okay thanks for your response @pandulapeter will keep this issue open for others

**Comment by pandulapeter** [comment]
Version 2.0.0 (now in alpha) will support Android versions down to API 16 (inclusive).

**Comment by adesamp** [comment]
using version : 2.0.0-alpha09

but still get error caused minSdk is 21 @pandulapeter :/

![image](https://user-images.githubusercontent.com/61401530/85267962-18ad5080-b4a0-11ea-9bcb-9da31432bf1d.png)

Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.github.pandulapeter.beagle:beagle:2.0.0-alpha09]

**Comment by mochadwi** [comment]
Have you try this approach in your base/dynamic module? https://stackoverflow.com/a/27310430/3763032 @adesamp

**Comment by pandulapeter** [comment]
The new version of the library uses a different dependency. Instead of the old:

```
    debugImplementation "com.github.pandulapeter.beagle:beagle:$beagleVersion"
    releaseImplementation "com.github.pandulapeter.beagle:beagle-noop:$beagleVersion"
```

...you will need the following:

```
    debugImplementation "com.github.pandulapeter.beagle:ui-bottom-sheet:$beagleVersion"
    releaseImplementation "com.github.pandulapeter.beagle:noop:$beagleVersion"
```

I did this so that the old version remains accessible as the new one has been rewritten from scratch. If you include these new dependencies, the minApi should be 16.

That being said, give me a few more days to propagate the library to beta: I'm still ironing out core functionality stuff, and some of the most useful features from the old version (network logging or logging for example) are not yet implemented. I've closed the issue because the new version fixes it, but I'd recommend waiting for a while until you update. I'm working on this actively right now so hopefully this week there will be a beta release.

For the time being, feel free to check out the [migration guide](https://github.com/pandulapeter/beagle/blob/master/metadata/MIGRATION_GUIDE.md) or clone this repository to see what's new :)

Sorry for the confusion!

**Comment by adesamp** [comment]
i have tried but still got error :/

**Comment by pandulapeter** [comment]
I'm sorry to hear that. Maybe clear the caches / do an invalidate & restart and double-check, as I'm pretty sure that the merged manifest for the new dependencies specifies minSdk 16. If you clone this repository and build the example app, it is also set to minimum 16.

I'll take a look at what else could have gone wrong but at this moment I cannot reproduce your issue, only with the old dependencies (the first block from my comment above - just to be clear: the new version is the second block).
