### ISSUE TITLE
Drawer views duplication

### ISSUE THREAD

**Issue by swalffy** [pandulapeter/beagle#70]
Hello, thank you for awesome library

Faced with the next issue additional drawer view is created and previous is not removed, after some steps. 
I've created small project to reproduce this issue. [Repo](https://github.com/swalffy/BeagleMultipleDrawers)
1) Launch app
2) Navigate between fragments via button
3) Check layout inspector (or child views of _androd.R.id.content_ ViewGroup)

Could you please take a look of this issue?

**Beagle: 2.3.9**

![layout inspector](https://user-images.githubusercontent.com/24682494/100111820-962a2200-2e7f-11eb-9a00-4bb7ee9ebf83.png)

**Comment by pandulapeter** [comment]
Thanks a lot for reporting this, I wasn't aware of the problem. That's an ugly one, I'll fix it ASAP.

**Comment by pandulapeter** [comment]
Quick update: this only seems to happen if you're using `android.R.id.content` as the container for your Fragments. With your repository I can reproduce the issue and hopefully the next version will contain a fix, just wanted to note that this should not be an issue for every project.

**Comment by pandulapeter** [comment]
The bug should be fixed in [release 2.4.0](https://github.com/pandulapeter/beagle/releases/tag/2.4.0), sorry it took so long. The way the debug menu is injected is different when Beagle has to share `android.R.id.content` as the Fragment container, it's not optimal but at least it should work. Let me know if you encounter any other issues and thanks again for finding this one and creating the example project!
