### ISSUE TITLE
Add ability to access to current activity from Beagle

### ISSUE THREAD

**Issue by egorikftp** [pandulapeter/beagle#8]
Hi, thanks for the great library. 
We faced some issue, that we need to access current activity to open some dialogs by clicking to Button trick.

How to make this behaviour correctly? Or the library can have a method like this:
`Beagle.currentActivity()`

Thanks a lot.

**Comment by pandulapeter** [comment]
Hi,

Thank you for raising this issue! It makes perfect sense, something like this should have been there from the beginning. One might say it's a bit hacky, but since it's not going to be used in production, why not...

[This commit](https://github.com/pandulapeter/beagle/commit/a13c32014a915b0a1b5fbb714d6ab5d88ae46fad) exposes the currentActivity property which always returns the most recently resumed Activity instance (or null if no such Activity exists). The new 1.4.3 release contains the changes.

Let me know if you find any other problems!
