### ISSUE TITLE
foregroundServiceType in the library forces targetSdk to at least 29

### ISSUE THREAD

**Issue by eric-labelle** [pandulapeter/beagle#83]
Not really an _issue_, but just pointing out that it is unfortunate that even if we do not use the `ScreenshotButtonModule` we need to `targetSDK 29` in order to use this library because of the usage of a `foregroundServiceType` here https://github.com/pandulapeter/beagle/blob/35b4b33a9758a8da59671a268334e412d161002a/internal-core/src/main/AndroidManifest.xml#L22

I believe if the `ScreenCaptureService` class was public we could use the `tools:node="remove"` in our manifest to ignore this service..

**Comment by pandulapeter** [comment]
Hi!

I usually try to keep `targetSdkVersion` up to date in my projects, but I understand that this might not be possible everywhere.

I did some testing with `targetSdkVersion 28` and turns out that you can remove the Service, even though it's encapsulated in the library (the IDE shows an error but it compiled for me...). Give this a try:

```
        <service
            android:name="com.pandulapeter.beagle.core.util.ScreenCaptureService"
            android:exported="false"
            tools:node="replace"/>
```

That being said:
1) That class will NOT be there for the `noop` implementation, so your release build will probably fail to compile / crash at runtime...?
2) I never tested the library with outdated targetSdkVersions, there might be other issues you encounter

There is a solution to the first problem, something I recommend for complex project anyway. Don't use Beagle directly, but create a wrapper module instead. That way you encapsulate all my API-s behind an interface, and provide your own `noop` implementation that doesn't even contain my `noop`. Check out how I did it in [this project](https://github.com/pandulapeter/spray-app) (`presentation:debugMenu` module)

Let me know how it goes!

**Comment by eric-labelle** [comment]
Thanks, it seems to be working with the service removal through the manifest but I still think it would be better to only have to bump to api29 if we actually would use this ScreenCapture module.

**Comment by pandulapeter** [comment]
I definitely agree that I shouldn't require api30 if you don't use api30 features - unfortunately the modularization of the library is still not granular enough to make this possible (the only way would be for the screenshot feature to be a separate artifact, which is a bit tricky to do now).

With Android 12 (api 31) right around the corner and the Play Store requiring newer and newer target SDK versions, I hope this problem is a temporary one, as sooner or later everybody will have to upgrade. For now, it's stated in my readme as a requirement and sounds like we have a workaround for your problem, so I'm closing the issue. Let me know if anything else comes up!

**Comment by eric-labelle** [comment]
Yeah, we don't have this requirement since our application is not distributed through the playstore ;)
