### ISSUE TITLE
Possibility to change the width of the drawer

### ISSUE THREAD

**Issue by SotirisAtSeb** [pandulapeter/beagle#98]
Thanks for such a useful library!

I was wondering if it is possible to change the width of the right-side drawer. Is there such a possibility? Which parts of the code control the width of the view that shows up at the drawer?

**Comment by pandulapeter** [comment]
Hi!

**Short answer:** It's not possible at the moment but I'll add it in the next version, soon.

**Long answer:** If you look at how the [internal module structure](https://raw.githubusercontent.com/pandulapeter/beagle/master/metadata/modules.png) of the library works, you'll see that I designed myself into a corner. The public API of Beagle is defined in an abstract way, so that it can work with any UI implementation: dialog, drawer, bottom sheet, etc. The disadvantage of this approach is that it's "ugly" to introduce API-s that only make sense for a single UI type, such as the width of the drawer (the idea is that consumers can switch the UI artifact at any time and everything will just work, without having to change the Kotlin code).

That being said, I'm aware that most people use the drawer UI so I already started introducing drawer-specific customization options that simply don't do anything for the other UI types. One example is `Behavior.shouldLockDrawer` - I'll add something similar for the width of the drawer too in the next version.

If you're interested, the current size of the drawer is controlled by [DebugMenuDrawerLayout line 83](https://github.com/pandulapeter/beagle/blob/03c763d3af6d592a95ce12df5f0887079c2b94e4/ui-drawer/src/main/java/com/pandulapeter/beagle/logCrash/implementation/DebugMenuDrawerLayout.kt#L83) which sets it to `min(screenWidth*0.6, 320dp)`.

I'll update this thread once this new feature is released, thanks for the idea!

**Comment by pandulapeter** [comment]
[Release 2.6.7](https://github.com/pandulapeter/beagle/releases/tag/2.6.7) now contains a way to set a custom size for the drawer through the `Behavior` object's `getDrawerSize()` lambda. Usage:

```
Beagle.initialize(
    ...
    behavior = Behavior(
        getDrawerSize = { _, screenWidth -> screenWidth / 2 }
        // OR: getDrawerSize = { context, _ -> context.getDimensionPixelSize(R.dimen.your_drawer_width) }
        // OR: getDrawerSize = { _, _ -> DRAWER_WIDTH_IN_PIXELS }
    ...
    )
)
```
